DROP DATABASE IF EXISTS burgers_db;
CREATE DATABASE burgers_db;

USE burger_db;

DROP TABLE IF EXISTS burgers;
CREATE TABLE burgers (
	id INTEGER (11) AUTO_INCREMENT NOT NULL,
	PRIMARY KEY (id),
	burger_name VARCHAR (100) NOT NULL,
	devoured BOOLEAN DEFAULT false,
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
